<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="2.914" timestamp="2024-04-23T02:32:27.020736" hostname="sebastiancg"><testcase classname="" name="tests.api.test_api" time="0.000"><error message="collection failure">ImportError while importing test module 'G:\My Drive\GitHub\proj-challenge-LATAM\tests\api\test_api.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Users\sebastiancg\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\api\test_api.py:4: in &lt;module&gt;
    from challenge import app
challenge\__init__.py:1: in &lt;module&gt;
    from challenge.api import app
challenge\api.py:5: in &lt;module&gt;
    from model import DelayModel
E   ModuleNotFoundError: No module named 'model'</error></testcase></testsuite></testsuites>